[package]
name = "csv_transaction_processor"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1.6"
tokio = { version = "1.19.2", features = ["full"] }
tokio-stream = "0.1.9"
log = "0.4"
pretty_env_logger = "0.4.0"